set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Avoid a name conflict with L9
" Plugin 'user/L9', {'name': 'newL9'}

" Tools (sorted)
Plugin 'godlygeek/tabular'    " :Tabularize motion
Plugin 'groenewege/vim-less'
Plugin 'mattn/gist-vim' " :Gist
Plugin 'tpope/vim-commentary' " gc(motion, gc to undo)
Plugin 'tpope/vim-fugitive' " :Gedit :Gsplit :Gvsplit :Gdiff
Plugin 'tpope/vim-repeat' " makes . repeat plugin commands defined by tpope
Plugin 'tpope/vim-scriptease'
Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-speeddating' " ^A ^D on dates, e.g., Oct 10, 1981
Plugin 'tpope/vim-surround' " cs old quote new quote
Plugin 'tpope/vim-unimpaired' " :help unimpaired
Plugin 'tpope/vim-vinegar' " - up, . command ! command ~ home cg cl to cd or lcd

" File types
Plugin 'alunny/pegjs-vim'
Plugin 'elzr/vim-json'
Plugin 'othree/html5.vim'
Plugin 'solarnz/thrift.vim'

" Color schemes
Plugin 'baycomb'
Plugin 'w0ng/vim-hybrid'

" All of your Plugins must be added before the following line
call vundle#end()         " required
" load the plugin and indent settings for the detected filetype
filetype plugin indent on " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Regarding the HUD
let mapleader=";"
set number
set ruler
set scrolloff=3
set laststatus=2
set mouse=a
syntax on

" Regarding space
set autoindent
set expandtab
set nowrap
set shiftwidth=4
set softtabstop=4
set tabstop=4
" allow backspacing over everything in insert mode
set backspace=indent,eol,start
filetype indent on
" Makefile, respect tabs
au FileType make set noexpandtab
" Python, follow PEP8 ( http://www.python.org/dev/peps/pep-0008/ )
au FileType python set softtabstop=4 tabstop=4 shiftwidth=4 textwidth=79

" Searching
set incsearch
set hlsearch
"set ignorecase
"set smartcase
" % to bounce from do to end etc.
runtime! macros/matchit.vim

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

" Color
set background=dark
colorscheme hybrid " from vim-hybrid

" Backups
set noswapfile
" Alternately,
" Directories for swp files
" set backupdir=~/.vim/backup
" set directory=~/.vim/backup
" Make uses real tabs

" fugitive:
" set statusline=%{fugitive#statusline()}

" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

" Use modeline overrides
set modeline
set modelines=10

" Include user's local vim config
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
